In [11]:
# 2
import torch
X = torch.rand(7, 7)
X

tensor([[0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018],
        [0.9497, 0.6666, 0.9811, 0.0874, 0.0041, 0.1088, 0.1637],
        [0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057],
        [0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313],
        [0.3227, 0.0162, 0.2137, 0.6249, 0.4340, 0.1371, 0.5117]])

In [24]:
# 3
Y = torch.rand(1, 7)
Y

tensor([[0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770]])

In [13]:
torch.matmul(X, Y.T)

tensor([[0.9949],
        [0.6062],
        [0.6337],
        [1.3547],
        [1.3971],
        [1.5137],
        [0.6594]])

In [15]:
# 4
SEED = 0
torch.manual_seed(SEED)
X = torch.rand(7, 7)
Y = torch.rand(1, 7)
X@Y.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [16]:
# 5
torch.cuda.manual_seed(1234)

In [29]:
# 6
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(1234)
X = torch.rand(2, 3).to(device)
Y = torch.rand(2, 3).to(device)

print(X)
print(Y)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [32]:
# 7
Z = X@Y.T
Z

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [35]:
# 8
print(Z.min(), Z.max())

tensor(0.3647, device='cuda:0') tensor(0.5617, device='cuda:0')


In [36]:
# 9
print(Z.argmin(), Z.argmax())

tensor(0, device='cuda:0') tensor(3, device='cuda:0')


In [38]:
torch.argmax(Z)

tensor(3, device='cuda:0')

In [39]:
# 10
torch.manual_seed(7)
X = torch.rand(1, 1, 1, 10)
Y = X.squeeze()

print(X, X.shape)
print(Y, Y.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
