In [1]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

# Check for GPU (should return True)
print(torch.cuda.is_available())

C:\Users\kakas\AppData\Local\Programs\Python\Python310\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")


True


## Introduction to tensors
### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim # rank 0 tensor

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 2])
vector

tensor([7, 2])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 1], 
                       [2,3]])
MATRIX

tensor([[7, 1],
        [2, 3]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                      
                      [[-1, -2, -3],
                      [-4, -5, -6],
                      [-7, -8, -9]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[-1, -2, -3],
         [-4, -5, -6],
         [-7, -8, -9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([2, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
TENSOR[1]

tensor([[-1, -2, -3],
        [-4, -5, -6],
        [-7, -8, -9]])

### Random tensors

Random tensors are important because many neural networks start learning using a tensor full of random numbers

In [16]:
# Create a random tensor of size (3, 5)

random_tensor = torch.rand(3, 5)
random_tensor

tensor([[0.1033, 0.7624, 0.0317, 0.3870, 0.7884],
        [0.9082, 0.0921, 0.0473, 0.4308, 0.1766],
        [0.4332, 0.2313, 0.0928, 0.5199, 0.2296]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(5,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
random_tensor@zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
zero_to_ten = torch.arange(0 , 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
torch.arange(start=0, end=1000, step=42)

tensor([  0,  42,  84, 126, 168, 210, 252, 294, 336, 378, 420, 462, 504, 546,
        588, 630, 672, 714, 756, 798, 840, 882, 924, 966])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors we can run into with PyTorch & deep learning:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None, # cpu/cuda/mps
                               requires_grad=False) # track or not to track the gradients on this tensor

float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype # default dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

In [31]:
some_tensor = torch.rand(size=(3,5), dtype=torch.float16, device='cuda')
some_tensor

tensor([[0.7754, 0.7480, 0.4224, 0.6226, 0.8613],
        [0.5488, 0.0569, 0.3982, 0.5645, 0.4480],
        [0.2456, 0.7773, 0.4387, 0.9902, 0.0707]], device='cuda:0',
       dtype=torch.float16)

In [32]:
print(f"datatype: {some_tensor.dtype}\nshape: {some_tensor.shape}\ndevice: {some_tensor.device}")

datatype: torch.float16
shape: torch.Size([3, 5])
device: cuda:0


### Manipulating Tensors (tensor operations)

In [33]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [34]:
tensor + 10

tensor([11, 12, 13])

In [35]:
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor - 10

tensor([-9, -8, -7])

In [37]:
tensor ** 2

tensor([1, 4, 9])

In [38]:
tensor * tensor

tensor([1, 4, 9])

In [39]:
tensor@tensor

tensor(14)

In [40]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 993 µs


In [41]:
%%time
torch.matmul(tensor, tensor) # tensor@tensor

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [47]:
torch.matmul(torch.rand(10, 2), torch.rand(2,4)).shape # inner dimensions match, output is outer dimensions

torch.Size([10, 4])

In [49]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5,6]])

tensor_B = torch.tensor([[8, 11],
                        [9, 12],
                        [10, 13]])

In [53]:
# tensor_A@tensor_B - error bad shape

In [54]:
tensor_B.T

tensor([[ 8,  9, 10],
        [11, 12, 13]])

In [55]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 30,  33,  36],
        [ 68,  75,  82],
        [106, 117, 128]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [56]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [58]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [62]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # torch.mean() requires float32 dtype to work

(tensor(45.), tensor(45.))

In [63]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [66]:
torch.argmax(x), torch.argmin(x) # find the position in tensor with max or min value and return the index

(tensor(9), tensor(0))

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [70]:
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [71]:
# Add an extra dimension
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [72]:
# Change the view
z = x.view(10, 1)
z, z.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [75]:
# changing z changes x (view of a tensor shares the same memory as original) - it's like a pointer
z[0, 0] = 99
z, x

(tensor([[99.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [79]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[99., 99., 99., 99.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [80]:
# torch.squeeze() - removes all single dimensions

In [88]:
x_reshaped

tensor([[99.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [83]:
x_reshaped.shape

torch.Size([5, 2])

In [86]:
x_reshaped.squeeze()

tensor([[99.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [93]:
x = torch.arange(1, 10).reshape(1, 9)
x, x.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [94]:
x_squeezed = x.squeeze()
x_squeezed, x_squeezed.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [100]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
x_squeezed.unsqueeze(dim=0), x_squeezed.unsqueeze(dim=0).shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [101]:
x_squeezed.unsqueeze(dim=1), x_squeezed.unsqueeze(dim=1).shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [103]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(244, 244, 3)) # height width color_channels
print(x_original.shape)

torch.Size([244, 244, 3])


In [106]:
# permute the original to rearrange dim order
x_permuted = x_original.permute(2, 0, 1) # returns a view of the x_original!!!!
x_permuted.shape # color_channel is now first!

torch.Size([3, 244, 244])

In [111]:
x_permuted[0,0,0] = 123414

In [113]:
torch.set_printoptions(sci_mode=False)
x_original

tensor([[[123414.0000,     0.7620,     0.5622],
         [    0.1199,     0.3485,     0.8775],
         [    0.6021,     0.0644,     0.0709],
         ...,
         [    0.9042,     0.5080,     0.8926],
         [    0.2353,     0.4570,     0.2766],
         [    0.1048,     0.0168,     0.7460]],

        [[    0.0000,     0.5069,     0.9402],
         [    0.8050,     0.6908,     0.3894],
         [    0.6134,     0.7141,     0.9755],
         ...,
         [    0.5103,     0.5898,     0.0712],
         [    0.0069,     0.2058,     0.2281],
         [    0.4592,     0.5886,     0.5003]],

        [[    0.1643,     0.1216,     0.4255],
         [    0.5077,     0.8966,     0.2551],
         [    0.8222,     0.1700,     0.7362],
         ...,
         [    0.0277,     0.2265,     0.4021],
         [    0.7578,     0.6315,     0.2843],
         [    0.4524,     0.3716,     0.9156]],

        ...,

        [[    0.2321,     0.5774,     0.8490],
         [    0.4701,     0.2542,     0.4259

### Indexing (selecting data from tensors)

In [114]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [116]:
x[0][1][1]

tensor(5)

In [119]:
x[:, :, 0]

tensor([[1, 4, 7]])

### PyTorch tensors & NumPy

In [2]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
array.dtype # default numpy dtype is float64 wheras pytorches is float32

dtype('float64')

In [4]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility
https://pytorch.org/docs/stable/notes/randomness.html

In [5]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


### GPU
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [6]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [7]:
torch.cuda.device_count()

1

In [9]:
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [11]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [13]:
# Setting GPU tensor to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)